name: uv-kmahub
on:
  schedule:
    - cron: "*/10 * * * *"   # 10분마다
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      INFLUX_URL:    ${{ secrets.INFLUX_URL }}
      INFLUX_TOKEN:  ${{ secrets.INFLUX_TOKEN }}
      INFLUX_ORG:    ${{ secrets.INFLUX_ORG }}
      INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      APIHUB_KEY:    ${{ secrets.APIHUB_KEY }}
      APIHUB_BASE:   ${{ vars.APIHUB_BASE }}
      UV_STN:        ${{ vars.UV_STN }}
      LOC:           ${{ vars.LOC || 'seoul' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm i -D typescript ts-node dotenv-cli @types/node
      - run: npm i iconv-lite

      - name: Jitter (scheduled only)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          # 60~120초 랜덤 대기
          sleep $((RANDOM % 61 + 60))

      - run: npx ts-node scripts/uv_to_influx.ts
